from .command import run_cmd

def apply_linear_transform(subject_name: str, file_path: str, transform_path: str, reference_img_path: str, output_path: str) -> int:
    """Applies linear affine and rigid transform from a matlab file generated by antsRegistration

    Args:
        subject_name (str): Name of subject
        file_path (str): Path to file which the transform is being applied to
        transform_path (str): Path to transform .mat file
        reference_img_path (str): Registered reference image
        output_path (str): Path to put the resulting transformed image

    Returns:
        int: o on success, non-zero on fail
    """
    cmd = f'antsApplyTransforms --dimensionality 3 --float 0 --input {file_path} --output {output_path} --reference-image {reference_img_path} --interpolation NearestNeighbor --transform [{transform_path}, 0]'

    _, err, code = run_cmd(cmd)

    if code != 0:
        print(f'Error for {subject_name}: could not apply transform {transform_path} to {file_path}:\n{err}')
    
    return code